name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  buildBackEnd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: Deploy backend/server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_SERVER}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_ORIGIN: "https://hololivechecker.netlify.app"
          HD_SELF: "https://hololivelive-api.herokuapp.com"
          HD_APP_BASE: "/client"

  buildFrontEnd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm install && npm run build --if-present

      - name: Deploy fe/client to netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./client/build"
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
