name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  buildBackEnd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: Deploy backend/server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_SERVER}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_ORIGIN: "https://hololivechecker.netlify.app"
          HD_SELF: "https://hololivelive-api.herokuapp.com"
          HD_APP_BASE: "/server"
