name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  buildBackEnd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Deploy backend/server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_SERVER}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_ORIGIN: "https://hololivechecker.netlify.app"
          HD_SELF: "https://hololivelive-api.herokuapp.com"

  buildFrontEnd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Use Node.js 12.x
        with:
          node-version: 12.x
        run: npm install
        run: npm run build --if-present

      - name: Deploy fe/client to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
          REACT_APP_BASE_URL: "https://hololivelive-api.herokuapp.com/api"
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
